package exercise.java_gui;

import java.util.*;

/**
 *
 * @author Fahmi Ahmad Fadilah
 */
public class PemesananView extends javax.swing.JFrame {

    // Deklarasi variabel
    private String nama, alamat, telepon, tempStr;
    private int totalPembelian;
    private int hargaAyamBakar, hargaNasiGoreng, hargaGurameBakar, hargaMieGoreng;
    private int hargaTehManis, hargaTehTarik, hargaJusAlpukat, hargaKopiLuwak;
    List<String> pesanan = new ArrayList<String>();

    /**
     * Creates new form PemesananView
     */
    public PemesananView() {
        // Inisialisasi Komponen
        initComponents();
        // Inisialisasi Variabel
        hargaAyamBakar = 15000;
        hargaNasiGoreng = 10000;
        hargaGurameBakar = 50000;
        hargaMieGoreng = 5000;
        hargaTehManis = 3000;
        hargaTehTarik = 6000;
        hargaJusAlpukat = 10000;
        hargaKopiLuwak = 8000;
        totalPembelian = 0;
        nama = "";
        alamat = "";
        telepon = "";
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        upperBackground = new javax.swing.JPanel();
        titleBackground = new javax.swing.JPanel();
        aplikasiTitle = new javax.swing.JLabel();
        customerBackground = new javax.swing.JPanel();
        customerTitle = new javax.swing.JLabel();
        customerNamaText = new javax.swing.JLabel();
        customerAlamatText = new javax.swing.JLabel();
        customerTeleponText = new javax.swing.JLabel();
        customerNamaValue = new javax.swing.JTextField();
        customerTeleponValue = new javax.swing.JTextField();
        customerAlamatValue = new javax.swing.JTextField();
        menuBackground = new javax.swing.JPanel();
        menuTitle = new javax.swing.JLabel();
        menuAyamBakar = new javax.swing.JCheckBox();
        menuNasiGoreng = new javax.swing.JCheckBox();
        menuGurameBakar = new javax.swing.JCheckBox();
        menuMieGoreng = new javax.swing.JCheckBox();
        menuTehManis = new javax.swing.JCheckBox();
        menuTehTarik = new javax.swing.JCheckBox();
        menuJusAlpukat = new javax.swing.JCheckBox();
        menuKopiLuwak = new javax.swing.JCheckBox();
        totalTitle = new javax.swing.JLabel();
        totalValue = new javax.swing.JTextField();
        tambahButton = new javax.swing.JButton();
        dataPenjualanPane = new javax.swing.JScrollPane();
        dataPenjualanValue = new javax.swing.JTextArea();
        dataPenjualanTitle = new javax.swing.JLabel();
        lowerBackground = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        upperBackground.setBackground(new java.awt.Color(51, 153, 255));
        upperBackground.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));

        titleBackground.setBackground(new java.awt.Color(255, 255, 255));
        titleBackground.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        titleBackground.setPreferredSize(new java.awt.Dimension(350, 68));

        aplikasiTitle.setBackground(new java.awt.Color(255, 255, 255));
        aplikasiTitle.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        aplikasiTitle.setForeground(new java.awt.Color(0, 0, 0));
        aplikasiTitle.setText("APLIKASI PEMESANAN");

        javax.swing.GroupLayout titleBackgroundLayout = new javax.swing.GroupLayout(titleBackground);
        titleBackground.setLayout(titleBackgroundLayout);
        titleBackgroundLayout.setHorizontalGroup(
            titleBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, titleBackgroundLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(aplikasiTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        titleBackgroundLayout.setVerticalGroup(
            titleBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, titleBackgroundLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(aplikasiTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        customerBackground.setBackground(new java.awt.Color(255, 255, 255));
        customerBackground.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        customerTitle.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        customerTitle.setForeground(new java.awt.Color(0, 0, 0));
        customerTitle.setText("DATA CUSTOMER");

        customerNamaText.setForeground(new java.awt.Color(0, 0, 0));
        customerNamaText.setText("Nama    : ");

        customerAlamatText.setForeground(new java.awt.Color(0, 0, 0));
        customerAlamatText.setText("Alamat  :");

        customerTeleponText.setForeground(new java.awt.Color(0, 0, 0));
        customerTeleponText.setText("No Telp :");

        customerNamaValue.setBackground(new java.awt.Color(255, 255, 255));
        customerNamaValue.setToolTipText("");

        customerTeleponValue.setBackground(new java.awt.Color(255, 255, 255));
        customerTeleponValue.setToolTipText("");
        customerTeleponValue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customerTeleponValueActionPerformed(evt);
            }
        });

        customerAlamatValue.setBackground(new java.awt.Color(255, 255, 255));
        customerAlamatValue.setToolTipText("");

        javax.swing.GroupLayout customerBackgroundLayout = new javax.swing.GroupLayout(customerBackground);
        customerBackground.setLayout(customerBackgroundLayout);
        customerBackgroundLayout.setHorizontalGroup(
            customerBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, customerBackgroundLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(customerBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(customerTeleponText)
                    .addComponent(customerAlamatText)
                    .addGroup(customerBackgroundLayout.createSequentialGroup()
                        .addComponent(customerNamaText)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGroup(customerBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(customerBackgroundLayout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(customerTeleponValue, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(customerAlamatValue, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(customerNamaValue, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(customerBackgroundLayout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addComponent(customerTitle)
                .addGap(0, 75, Short.MAX_VALUE))
        );
        customerBackgroundLayout.setVerticalGroup(
            customerBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(customerBackgroundLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(customerTitle)
                .addGap(24, 24, 24)
                .addGroup(customerBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(customerNamaText)
                    .addComponent(customerNamaValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(customerBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(customerAlamatText)
                    .addComponent(customerAlamatValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addGroup(customerBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(customerTeleponText)
                    .addComponent(customerTeleponValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41))
        );

        menuBackground.setBackground(new java.awt.Color(255, 255, 255));
        menuBackground.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        menuTitle.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        menuTitle.setForeground(new java.awt.Color(0, 0, 0));
        menuTitle.setText("MENU RESTORAN");

        menuAyamBakar.setBackground(new java.awt.Color(255, 255, 255));
        menuAyamBakar.setForeground(new java.awt.Color(0, 0, 0));
        menuAyamBakar.setText("Ayam Bakar");
        menuAyamBakar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuAyamBakarActionPerformed(evt);
            }
        });

        menuNasiGoreng.setBackground(new java.awt.Color(255, 255, 255));
        menuNasiGoreng.setForeground(new java.awt.Color(0, 0, 0));
        menuNasiGoreng.setText("Nasi Goreng");
        menuNasiGoreng.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuNasiGorengActionPerformed(evt);
            }
        });

        menuGurameBakar.setBackground(new java.awt.Color(255, 255, 255));
        menuGurameBakar.setForeground(new java.awt.Color(0, 0, 0));
        menuGurameBakar.setText("Gurame Bakar");
        menuGurameBakar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuGurameBakarActionPerformed(evt);
            }
        });

        menuMieGoreng.setBackground(new java.awt.Color(255, 255, 255));
        menuMieGoreng.setForeground(new java.awt.Color(0, 0, 0));
        menuMieGoreng.setText("Mie Goreng");
        menuMieGoreng.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuMieGorengActionPerformed(evt);
            }
        });

        menuTehManis.setBackground(new java.awt.Color(255, 255, 255));
        menuTehManis.setForeground(new java.awt.Color(0, 0, 0));
        menuTehManis.setText("Teh Manis");
        menuTehManis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuTehManisActionPerformed(evt);
            }
        });

        menuTehTarik.setBackground(new java.awt.Color(255, 255, 255));
        menuTehTarik.setForeground(new java.awt.Color(0, 0, 0));
        menuTehTarik.setText("Teh Tarik");
        menuTehTarik.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuTehTarikActionPerformed(evt);
            }
        });

        menuJusAlpukat.setBackground(new java.awt.Color(255, 255, 255));
        menuJusAlpukat.setForeground(new java.awt.Color(0, 0, 0));
        menuJusAlpukat.setText("Just Alpukat");
        menuJusAlpukat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuJusAlpukatActionPerformed(evt);
            }
        });

        menuKopiLuwak.setBackground(new java.awt.Color(255, 255, 255));
        menuKopiLuwak.setForeground(new java.awt.Color(0, 0, 0));
        menuKopiLuwak.setText("Kopi Luwak");
        menuKopiLuwak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuKopiLuwakActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout menuBackgroundLayout = new javax.swing.GroupLayout(menuBackground);
        menuBackground.setLayout(menuBackgroundLayout);
        menuBackgroundLayout.setHorizontalGroup(
            menuBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuBackgroundLayout.createSequentialGroup()
                .addGroup(menuBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(menuBackgroundLayout.createSequentialGroup()
                        .addGap(103, 103, 103)
                        .addComponent(menuTitle))
                    .addGroup(menuBackgroundLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(menuBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(menuAyamBakar)
                            .addComponent(menuNasiGoreng)
                            .addComponent(menuGurameBakar)
                            .addComponent(menuMieGoreng))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                        .addGroup(menuBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(menuTehTarik)
                            .addComponent(menuTehManis)
                            .addComponent(menuJusAlpukat)
                            .addComponent(menuKopiLuwak))))
                .addGap(47, 47, 47))
        );
        menuBackgroundLayout.setVerticalGroup(
            menuBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuBackgroundLayout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(menuTitle)
                .addGap(15, 15, 15)
                .addGroup(menuBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(menuAyamBakar)
                    .addComponent(menuTehManis))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(menuBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(menuNasiGoreng)
                    .addComponent(menuTehTarik))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(menuBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(menuGurameBakar)
                    .addComponent(menuJusAlpukat))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(menuBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(menuMieGoreng)
                    .addComponent(menuKopiLuwak))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        totalTitle.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        totalTitle.setForeground(new java.awt.Color(0, 0, 0));
        totalTitle.setText("TOTAL PEMBAYARAN");

        totalValue.setEditable(false);
        totalValue.setBackground(new java.awt.Color(0, 0, 0));
        totalValue.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        totalValue.setForeground(new java.awt.Color(255, 255, 0));
        totalValue.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        totalValue.setText("Rp0");
        totalValue.setToolTipText("");
        totalValue.setCaretColor(new java.awt.Color(0, 0, 0));
        totalValue.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        totalValue.setSelectedTextColor(new java.awt.Color(0, 0, 0));
        totalValue.setSelectionColor(new java.awt.Color(0, 0, 0));

        tambahButton.setBackground(new java.awt.Color(51, 255, 0));
        tambahButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        tambahButton.setForeground(new java.awt.Color(0, 0, 0));
        tambahButton.setText("TAMBAH");
        tambahButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        tambahButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tambahButtonActionPerformed(evt);
            }
        });

        dataPenjualanValue.setEditable(false);
        dataPenjualanValue.setBackground(new java.awt.Color(255, 255, 255));
        dataPenjualanValue.setColumns(20);
        dataPenjualanValue.setForeground(new java.awt.Color(0, 0, 0));
        dataPenjualanValue.setRows(5);
        dataPenjualanPane.setViewportView(dataPenjualanValue);

        dataPenjualanTitle.setBackground(new java.awt.Color(255, 255, 255));
        dataPenjualanTitle.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        dataPenjualanTitle.setForeground(new java.awt.Color(0, 0, 0));
        dataPenjualanTitle.setText("DATA PENJUALAN");

        javax.swing.GroupLayout upperBackgroundLayout = new javax.swing.GroupLayout(upperBackground);
        upperBackground.setLayout(upperBackgroundLayout);
        upperBackgroundLayout.setHorizontalGroup(
            upperBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, upperBackgroundLayout.createSequentialGroup()
                .addGap(0, 15, Short.MAX_VALUE)
                .addGroup(upperBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(dataPenjualanTitle)
                    .addGroup(upperBackgroundLayout.createSequentialGroup()
                        .addComponent(dataPenjualanPane, javax.swing.GroupLayout.PREFERRED_SIZE, 585, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(14, 14, 14))))
            .addGroup(upperBackgroundLayout.createSequentialGroup()
                .addGroup(upperBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(tambahButton, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(upperBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(upperBackgroundLayout.createSequentialGroup()
                            .addGap(200, 200, 200)
                            .addComponent(titleBackground, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(upperBackgroundLayout.createSequentialGroup()
                            .addGap(15, 15, 15)
                            .addComponent(customerBackground, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(21, 21, 21)
                            .addComponent(menuBackground, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, upperBackgroundLayout.createSequentialGroup()
                            .addGap(309, 309, 309)
                            .addGroup(upperBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(totalTitle)
                                .addComponent(totalValue, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        upperBackgroundLayout.setVerticalGroup(
            upperBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(upperBackgroundLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(titleBackground, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addGroup(upperBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(customerBackground, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(menuBackground, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addComponent(totalTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(totalValue, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tambahButton, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addComponent(dataPenjualanTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dataPenjualanPane, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        getContentPane().add(upperBackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 620, 790));

        lowerBackground.setBackground(new java.awt.Color(0, 102, 255));
        lowerBackground.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));

        javax.swing.GroupLayout lowerBackgroundLayout = new javax.swing.GroupLayout(lowerBackground);
        lowerBackground.setLayout(lowerBackgroundLayout);
        lowerBackgroundLayout.setHorizontalGroup(
            lowerBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 634, Short.MAX_VALUE)
        );
        lowerBackgroundLayout.setVerticalGroup(
            lowerBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 804, Short.MAX_VALUE)
        );

        getContentPane().add(lowerBackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 640, 810));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void customerTeleponValueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customerTeleponValueActionPerformed
        tempStr = customerTeleponValue.getText();
        if (tempStr.matches("[0-9]+") && tempStr.length() <= 13) {
            telepon = tempStr;
        } else {
            customerTeleponValue.setText("");
            telepon = "";
        }
    }//GEN-LAST:event_customerTeleponValueActionPerformed

    private void menuAyamBakarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuAyamBakarActionPerformed
        if (menuAyamBakar.isSelected()) {
            totalPembelian += hargaAyamBakar;
            pesanan.add("Ayam Bakar");
        } else {
            totalPembelian -= hargaAyamBakar;
            pesanan.remove("Ayam Bakar");
        }
        totalValue.setText("Rp" + totalPembelian + ",00");
    }//GEN-LAST:event_menuAyamBakarActionPerformed

    private void menuNasiGorengActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuNasiGorengActionPerformed
        if (menuNasiGoreng.isSelected()) {
            totalPembelian += hargaNasiGoreng;
            pesanan.add("Nasi Goreng");
        } else {
            totalPembelian -= hargaNasiGoreng;
            pesanan.remove("Nasi Goreng");
        }
        totalValue.setText("Rp" + totalPembelian + ",00");
    }//GEN-LAST:event_menuNasiGorengActionPerformed

    private void menuGurameBakarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuGurameBakarActionPerformed
        if (menuGurameBakar.isSelected()) {
            totalPembelian += hargaGurameBakar;
            pesanan.add("Gurame Bakar");
        } else {
            totalPembelian -= hargaGurameBakar;
            pesanan.remove("Gurame Bakar");
        }
        totalValue.setText("Rp" + totalPembelian + ",00");
    }//GEN-LAST:event_menuGurameBakarActionPerformed

    private void menuMieGorengActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuMieGorengActionPerformed
        if (menuMieGoreng.isSelected()) {
            totalPembelian += hargaMieGoreng;
            pesanan.add("Mie Goreng");
        } else {
            totalPembelian -= hargaMieGoreng;
            pesanan.remove("Mie Goreng");
        }
        totalValue.setText("Rp" + totalPembelian + ",00");
    }//GEN-LAST:event_menuMieGorengActionPerformed

    private void menuTehManisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuTehManisActionPerformed
        if (menuTehManis.isSelected()) {
            totalPembelian += hargaTehManis;
            pesanan.add("Teh Manis");
        } else {
            totalPembelian -= hargaTehManis;
            pesanan.remove("Teh Manis");
        }
        totalValue.setText("Rp" + totalPembelian + ",00");
    }//GEN-LAST:event_menuTehManisActionPerformed

    private void menuTehTarikActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuTehTarikActionPerformed
        if (menuTehTarik.isSelected()) {
            totalPembelian += hargaTehTarik;
            pesanan.add("Teh Tarik");
        } else {
            totalPembelian -= hargaTehTarik;
            pesanan.remove("Teh Tarik");
        }
        totalValue.setText("Rp" + totalPembelian + ",00");
    }//GEN-LAST:event_menuTehTarikActionPerformed

    private void menuJusAlpukatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuJusAlpukatActionPerformed
        if (menuJusAlpukat.isSelected()) {
            totalPembelian += hargaJusAlpukat;
            pesanan.add("Jus Alpukat");
        } else {
            totalPembelian -= hargaJusAlpukat;
            pesanan.remove("Jus Alpukat");
        }
        totalValue.setText("Rp" + totalPembelian + ",00");
    }//GEN-LAST:event_menuJusAlpukatActionPerformed

    private void menuKopiLuwakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuKopiLuwakActionPerformed
        if (menuKopiLuwak.isSelected()) {
            totalPembelian += hargaKopiLuwak;
            pesanan.add("Kopi Luwak");
        } else {
            totalPembelian -= hargaKopiLuwak;
            pesanan.remove("Kopi Luwak");
        }
        totalValue.setText("Rp" + totalPembelian + ",00");
    }//GEN-LAST:event_menuKopiLuwakActionPerformed

    private void tambahButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tambahButtonActionPerformed
        String dataCustomer = "";
        String dataPesanan = "";
        nama = customerNamaValue.getText();
        alamat = customerAlamatValue.getText();
        telepon = customerAlamatValue.getText();
        if (nama.equals("") || alamat.equals("") || telepon.equals("")) {
            dataPenjualanValue.setText("Data Customer Belum Lengkap!");
        } else {
            dataCustomer = ("==================== CHECKOUT RESTORAN ====================\n"
                    + "\n---------------------------------------------------------------------------------------------------------"
                    + "\nNama           : " + nama
                    + "\nAlamat         : " + alamat
                    + "\nNo Telepon : " + telepon
                    + "\n---------------------------------------------------------------------------------------------------------"
                    + "\n========================== PESANAN =========================\n");
            for (int i = 0; i < pesanan.size(); i++) {
                    dataPesanan += "> " + pesanan.get(i) + "\n";
            }
            dataPenjualanValue.setText(dataCustomer + dataPesanan + "\nTotal Pembayaran: Rp" + totalPembelian + ",00");
        }
    }//GEN-LAST:event_tambahButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PemesananView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PemesananView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PemesananView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PemesananView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PemesananView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel aplikasiTitle;
    private javax.swing.JLabel customerAlamatText;
    private javax.swing.JTextField customerAlamatValue;
    private javax.swing.JPanel customerBackground;
    private javax.swing.JLabel customerNamaText;
    private javax.swing.JTextField customerNamaValue;
    private javax.swing.JLabel customerTeleponText;
    private javax.swing.JTextField customerTeleponValue;
    private javax.swing.JLabel customerTitle;
    private javax.swing.JScrollPane dataPenjualanPane;
    private javax.swing.JLabel dataPenjualanTitle;
    private javax.swing.JTextArea dataPenjualanValue;
    private javax.swing.JPanel lowerBackground;
    private javax.swing.JCheckBox menuAyamBakar;
    private javax.swing.JPanel menuBackground;
    private javax.swing.JCheckBox menuGurameBakar;
    private javax.swing.JCheckBox menuJusAlpukat;
    private javax.swing.JCheckBox menuKopiLuwak;
    private javax.swing.JCheckBox menuMieGoreng;
    private javax.swing.JCheckBox menuNasiGoreng;
    private javax.swing.JCheckBox menuTehManis;
    private javax.swing.JCheckBox menuTehTarik;
    private javax.swing.JLabel menuTitle;
    private javax.swing.JButton tambahButton;
    private javax.swing.JPanel titleBackground;
    private javax.swing.JLabel totalTitle;
    private javax.swing.JTextField totalValue;
    private javax.swing.JPanel upperBackground;
    // End of variables declaration//GEN-END:variables
}
